vich_uploader:
    db_driver: orm

    mappings:
        cour_image:
            uri_prefix: images/cour
            upload_destination: '%kernel.project_dir%/public/images/cour' 
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            delete_on_remove: false
            delete_on_update: false